### ISSUE TITLE
yazelix layout path

### ISSUE THREAD

**Issue by guttermonk** [luccahuguet/yazelix#53]
Incorrect filename or path, possibly? When I select "yazelix" as the layout, I get this error:

![Image](https://github.com/user-attachments/assets/e7544a26-be1f-4e79-a05b-72282851665a)

There is a "main.lua" at that path instead of the init.lua in the screenshot, or if you go up two directories there's an "init.lua" ...one of these may be correct.

.
.
.

PS: I had another error that the Kitty terminal was causing (got the same error with Zellij in Kitty) 
![Image](https://github.com/user-attachments/assets/57e4ef02-c7b9-41b0-95dd-e80ffd4e24e0)

Switching terminals fixed it, but the message made me wonder if yazelix had its own log files or if this error message was just coming from Zellij. I found the Zellij log files but couldn't find any yazelix logs. It would be helpful to add some info around this to the troubleshooting section.

For example, "Users might encounter error messages referencing logs. Those logs are specific to Zellij, as yazelix does not generate logs. The Zellij log is located at: /$temp_dir/zellij-<UID>/zellij-log/zellij.log. $temp_dir, in most systems will be /tmp, but there can be exceptions, such as /var/folders/dr/xxxxxxxxxxxxxx/T/ for Mac." ...or something to that effect.

Great to see the project still evolving. Keep up the great work.

**Comment by luccahuguet** [comment]
Good catch! will see if i can solve this today

thank you very much

yeah, yazelix is a bunch of projects glued with nushell and protocols, so could have logs on the nushell level, interesting idea

might add info on that on the documentation like you said

> Great to see the project still evolving. Keep up the great work.
Amem! it's a fun project and my daily driver so...

**Comment by luccahuguet** [comment]
try updating yazi

**Comment by luccahuguet** [comment]
i added something that might be useful in the docs

https://github.com/luccahuguet/yazelix?tab=readme-ov-file#table-of-versions-of-yazelix-v51-last-tested-frebuary-26th-2025

**Comment by luccahuguet** [comment]
after you fix it, tell me what you think of the new status bar

and send a screenshot if possible!

**Comment by guttermonk** [comment]
I was pretty sure I had the latest version of yazi installed, but just built and installed the most recent commit. Still getting the same errors, but thank you for the suggestion.

**Comment by luccahuguet** [comment]
oh boy

I might have to structure things in a different way then

its sad that it works on my machine and not on yours

did you git pull yazelix as well?

**Comment by luccahuguet** [comment]
Are you in nushell? you can try running the sidebar with YAZI_LOG set to "debug"

```
$env.YAZI_LOG = "debug"
env YAZI_CONFIG_HOME=/home/lucca/.config/yazelix/yazi/sidebar yazi
```

**Comment by luccahuguet** [comment]
i'll see if there is a yazi discord or something, to get more eyes at this

**Comment by luccahuguet** [comment]
lets give this a week and see it is solved

because it is really looking for a init.lua file that does not exist there, instead of the proper main.lua, that lies inside the plugin folder (`~/.config/yazelix/yazi/sidebar/plugins/sidebar-status.yazi/main.lua`)

and the new versions of yazi correctly look for the main.lua file (inside each plugin folder)

can you give me your `yazi --debug`?

**Comment by guttermonk** [comment]
I'm not really sure how to do all that with NixOS, but we can give it a week like you suggested. In the meantime, I was able to get [Zide](https://github.com/josephschmitt/zide) up and running. So if this issue is just me, please feel free to close it out.

Also, I just noticed that this project requires WezTerm or Ghostty. I was using it with Kitty, but that's having a [separate issue with Zellij](https://github.com/zellij-org/zellij/issues/3754) and then I tried Alacritty next which is my other go-to terminal. I noticed in Alacritty, I get a notification first before it goes to the original error message that says:
```
 Waiting to run: env YAZI_CONFIG_HOME=~/.config/yazelix/yazi/sidebar yazi
```
Not really sure if an environment variable needs to be added to either the Hyprland or NixOS config, but I think I'm in over my head here. Strange that it used to work fine.

**Comment by luccahuguet** [comment]
zide is cool! had no idea about that

this project should run with any shell, the only difference is that I tested with ghostty and wezterm, and i provide configs, but it should really work in any shell... I will make it clearer in the readme, thanks for bringing it up

Thanks for all the info, Gutter, this really helps

if others are going through this, we should discover soon. might be something with the interaction with nixos

well, I will tag you if I change something to the plugin

**Comment by luccahuguet** [comment]
@guttermonk i've made some changes in https://github.com/luccahuguet/yazelix/tree/plugin_exploration

improved a lot of stuff, and also got into the same bug as yours sometimes when i updated yazi or yazelix, but still had old instances of yazi running in other zellij session

so you could try this new branch (which is yazelix 5.4) and kill every instance of yazi/zellij that you had before updating, this should work...

`pkill -f yazi` or  `kill -9 $(pgrep -f yazi)`

**Comment by guttermonk** [comment]
Hi @luccahuguet, I tried the [latest commit to main](https://github.com/luccahuguet/yazelix/commit/fe9bbaee0b95b2cc448a8b3e62442c5259574561) and ran `kill -9 $(pgrep -f yazi)` before trying to open yazelix, but still get the same error when I select "yazelix" as the new session layout. 

It's strange, I don't see anything in the yazelix config files pointing to init.lua and I'm installing yazi directly from the latest commit to main as well. This has me stumped, but thank you for continuing to look into it.

**Comment by luccahuguet** [comment]
Thanks for trying!

The branch i mentioned is called plugin_exploration actually

But I will let you know I merge it to main then

Definitely a puzzle haha

**Comment by guttermonk** [comment]
I tried the [plugin_exploration](https://github.com/luccahuguet/yazelix/tree/plugin_exploration) branch and still got the same error.

The stack traceback says "in function 'require'" ...I wonder where that function is being called. Could it be an issue with yazi and custom layouts?

**Comment by luccahuguet** [comment]
im not a yazi expert but from my short experience, when many times when this error appears, it mean something in the lua code that got called is not working

in the plugin branch, this is the ~/.config/yazelix/yazi/init.lua file 

it calls for the plugins right at the top, with require:

```lua
require("sidebar-status"):setup()
require("git"):setup()

-- Function to get terminal width
local function get_terminal_width()
    local handle = io.popen("tput cols")
    local width = handle:read("*n")
    handle:close()
    return width or 80 -- Default to 80 if tput fails
end

-- Function to determine and set the layout
local function set_layout()
    local width = get_terminal_width()
    if width > 120 then
        sidebar_size = "big"
    elseif width > 80 then
        sidebar_size = "medium"
    else
        sidebar_size = "small"
    end

    -- Map size to layout
    local layout = (sidebar_size == "small") and "max-current" or "reset"
    require("toggle-pane"):entry(layout)
end

-- Apply layout on startup
set_layout()
```

it may not be finding the plugins code for some reason, or using the wrong lua version or something

i dont even have lua installed (if i run lua on my terminal, nothing happens) since yazi comes with it already

this could be a possibility...

also this could be of help: https://github.com/luccahuguet/yazelix/tree/plugin_exploration#table-of-versions

**Comment by luccahuguet** [comment]
hey @guttermonk, release v6 into main

if you wanna try again

there are more changes

**Comment by guttermonk** [comment]
Just updated to the latest release, but I'm still getting the same error unfortunately.

Am I the only one experiencing this? I must have configured something wrong.

**Comment by luccahuguet** [comment]
> Just updated to the latest release, but I'm still getting the same error unfortunately.

oh no..

> Am I the only one experiencing this? I must have configured something wrong.

yeah, at least that I know of..

now there is a logging section in the readme

and you could reinstall some of the programs, perhaps, remove old configs and start new ones...

maybe yazelix has problems with nixOS? 

and lastly, yazi has some sections on nix here: https://github.com/yazi-rs/yazi-rs.github.io/blob/main/docs/installation.md

**Comment by guttermonk** [comment]
I finally got it working. To make [a long story](https://discourse.nixos.org/t/enabling-package-in-home-manager-causes-it-to-use-an-old-version/62685/8) short, I had my home-manager module misconfigured and it wasn't pulling in the latest version of yazi that I had configured in the OS.

**Comment by luccahuguet** [comment]
awesome! im quite happy you finally did it

it may be a bit painful spending all these hours but you surely learned a lot in the process, so amem to that

i might use this discution as reference, if I get my hands dirt with nix stuff, which is something i plan to do in the future

anyways, great news
